### ISSUE TITLE
Load native library to class path

### ISSUE THREAD

**Issue by KamilSzelag** [DevelopersOrganizationFork/sensor#6]
Mam problem z dodaniem natywnych bibliotek potrzebnych do odpalenia biblioteki sigar.

```
3 [pool-1-thread-1] DEBUG Sigar  - no sigar-amd64-winnt.dll in java.library.path
org.hyperic.sigar.SigarException: no sigar-amd64-winnt.dll in java.library.path
    at org.hyperic.sigar.Sigar.loadLibrary(Sigar.java:172)
    at org.hyperic.sigar.Sigar.<clinit>(Sigar.java:100)
    at org.developers.sensor.source.SensorRunnable.createSystemInformation(SensorRunnable.java:38)
    at org.developers.sensor.source.SensorRunnable.run(SensorRunnable.java:27)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```

workaround - ustawić native library location: Sensor/libs

**Comment by Silwest** [comment]
Rozwiazanie:

Dodac do opcji VMki Javy 

-Djava.library.path="Path do sigar-amd64-winnt.dll"

**Comment by KamilSzelag** [comment]
Tak, wiem, ze tak można, ale ja chciałem to zrobić z poziomu mavena.
Tzn jak będziesz pobierał nowy projekt, dasz maven install i chciałbym, żeby wszystko się ustawiło.
Później już tylko compile i powinno działać, teraz tak nie jest trzeba ręcznie ustawić.

**Comment by salberski** [comment]
Mozna zawsze jakiegoś bat'a napisać do uruchomienia. 

----- Reply message -----
Od: "KamilSzelag" notifications@github.com
Do: "DevelopersOrganizationFork/sensor" sensor@noreply.github.com
Temat: [sensor] Load native library to class path (#6)
Data: czw., mar 12, 2015 13:00
Tak, wiem, ze tak można, ale ja chciałem to zrobić z poziomu mavena.

Tzn jak będziesz pobierał nowy projekt, dasz maven install i chciałbym, żeby wszystko się ustawiło.

Później już tylko compile i powinno działać, teraz tak nie jest trzeba ręcznie ustawić.

&mdash;
